version: '3'
services:
  m2t_rabbitmq:
    container_name: m2t_rabbitmq
    build: .
    image: mail2telegram/rabbitmq:dev
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
networks:
  default:
    external:
      name: m2t
